// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../sail/boot.js', [], ['sail.model.Group', 'sail.model.Space', 'sail.model.Sprite', 'sail.model.Ticker']);
goog.addDependency('../../../sail/model/group.js', ['sail.model.Group'], ['goog.graphics']);
goog.addDependency('../../../sail/model/space.js', ['sail.model.Space'], ['goog.graphics']);
goog.addDependency('../../../sail/model/sprite.js', ['sail.model.Sprite'], ['sail.model.Space']);
goog.addDependency('../../../sail/model/ticker.js', ['sail.model.Ticker'], ['goog.Timer', 'goog.events']);
